{
 "title": "Metering Of AliCloud",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(kube_namespace_labels{label_kind=\"customer\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "OSS",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 2608,
     "logsPerPage": 100,
     "query": "BucketName: $project* |SELECT * , ( SELECT max(Value)/1024/1024 FROM log T1 WHERE T1.cms_metric = 'MeteringStorageUtilization'  and T1.BucketName=T0.BucketName ) AS \"MeteringStorageUtilization\" , ( SELECT sum(T2.Value) FROM log T2 WHERE T2.cms_metric = 'MeteringGetRequest' and T2.BucketName=T0.BucketName ) AS \"MeteringGetRequest\" , ( SELECT sum(T3.Value) FROM log T3 WHERE T3.cms_metric = 'MeteringPutRequest' and T3.BucketName=T0.BucketName ) AS putAndOrtherRequest , ( SELECT sum(T5.Value)/1024/1024 FROM log T5 WHERE T5.cms_metric = 'InternetSend' and T5.BucketName=T0.BucketName) AS \"InternetSend\" FROM ( SELECT DISTINCT BucketName FROM log ) T0 GROUP BY BucketName order by BucketName",
     "target": "BucketName,MeteringStorageUtilization,MeteringGetRequest,putAndOrtherRequest,InternetSend",
     "totalPages": 27,
     "type": "table",
     "ycol": "BucketName,MeteringStorageUtilization,MeteringGetRequest,putAndOrtherRequest,InternetSend"
    }
   ]
  },
  {
   "title": "POD",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "container_name:$project*  | SELECT  namespace , container_name as name,cpu,memory, count(1) as count group by name, cpu, memory, namespace",
     "target": "namespace,name,cpu,memory,count",
     "type": "table",
     "ycol": "namespace,name,cpu,memory,count"
    }
   ]
  },
  {
   "title": "SLB",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 330,
     "logsPerPage": 100,
     "query": "loadBalancerName:$project*|  SELECT loadBalancerName AS name, PayType, InternetChargeType, Bandwidth, loadBalancerSpec , COUNT(1) AS count1, COUNT(1) AS count2 ,   round(sum(NetworkOut)/1024/1024/1024.0, 3) AS traffic   GROUP BY loadBalancerName, loadBalancerSpec, PayType, Bandwidth, InternetChargeType ORDER BY loadBalancerName",
     "target": "name,PayType, InternetChargeType ,Bandwidth,loadBalancerSpec,count1,count2,traffic",
     "totalPages": 4,
     "type": "table",
     "ycol": "name,PayType, InternetChargeType ,Bandwidth,loadBalancerSpec,count1,count2,traffic"
    }
   ]
  },
  {
   "title": "RDS",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 12 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 30,
     "logsPerPage": 100,
     "query": "dbinstancedescription:$project*  | SELECT dbinstancedescription, dbinstanceclass, dbinstancestorage, paytype, engine, count(1) as Count GROUP BY dbinstancedescription, dbinstanceclass, dbinstancestorage, paytype, engine",
     "target": "dbinstancedescription, dbinstanceclass, dbinstancestorage, paytype, engine, Count",
     "totalPages": 1,
     "type": "table",
     "ycol": "dbinstancedescription, dbinstanceclass, dbinstancestorage, paytype, engine, Count"
    }
   ]
  },
  {
   "title": "MongoDB",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 38,
     "logsPerPage": 100,
     "query": "DBInstanceDescription:$project* | SELECT DBInstanceDescription,DBInstanceType,DBInstanceId,DBInstanceClass,DBInstanceStorage,ChargeType,CreationTime,ExpireTime, count(1) as UsageTime group by DBInstanceDescription,DBInstanceType,DBInstanceId,DBInstanceClass,DBInstanceStorage,ChargeType,CreationTime,ExpireTime",
     "target": "DBInstanceDescription,DBInstanceType,DBInstanceClass,DBInstanceStorage,ChargeType,ExpireTime,UsageTime",
     "totalPages": 1,
     "type": "table",
     "ycol": "DBInstanceDescription,DBInstanceType,DBInstanceClass,DBInstanceStorage,ChargeType,ExpireTime,UsageTime"
    }
   ]
  },
  {
   "title": "API Gaterway",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 19 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 663,
     "logsPerPage": 100,
     "query": "* | SELECT apiGroupName, instanceId, COUNT(1) as Count, sum(responseSize) as ResponseSize GROUP BY apiGroupName, instanceId",
     "target": "apiGroupName, instanceId, Count, ResponseSize",
     "totalPages": 7,
     "type": "table",
     "ycol": "apiGroupName, instanceId, Count, ResponseSize"
    }
   ]
  },
  {
   "title": "SecretManagement",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "currentPage": 1,
     "logsPerPage": 100,
     "query": "namespace:$project*  |  SELECT  namespace, secret_management_name as name, count(1) as count group by name , namespace",
     "target": "namespace,name,count",
     "type": "table",
     "ycol": "namespace,name,count"
    },
    { "currentPage": 1, "logsPerPage": 100, "type": "table" }
   ]
  },
  {
   "title": "Redis",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 27 },
   "targets": [
    {
     "currentPage": 1,
     "logEntries": 144,
     "logsPerPage": 100,
     "query": "InstanceName:$project* |  SELECT  InstanceName,InstanceId, InstanceClass , max(Bandwidth) as bandwidth , DefaultBandWidth , count(1) as count group by InstanceName , InstanceId,InstanceClass,Bandwidth, DefaultBandWidth",
     "target": "InstanceName,InstanceId,InstanceClass,bandwidth,count",
     "totalPages": 2,
     "type": "table",
     "ycol": "InstanceName,InstanceId,InstanceClass,bandwidth,DefaultBandWidth,count"
    }
   ]
  }
 ]
}